# Generated by Django 5.1.2 on 2025-04-16 03:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=500)),
                ('document_uploaddate', models.DateField(default=django.utils.timezone.now)),
                ('document_path', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('judul_artikel', models.CharField(max_length=500)),
                ('ekstrak_teks', models.TextField()),
                ('tokenisasi', models.TextField()),
                ('kueri_ocr', models.TextField()),
                ('pelatihan_model', models.TextField()),
                ('perhitungan_vektor_dokumen', models.TextField()),
                ('perhitungan_kueri_ocr', models.TextField()),
                ('perhitungan_kesamaan_kosinus', models.FloatField()),
                ('keterangan', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'results',
                'ordering': ['id'],
            },
        ),
    ]
